# WhatATheme
markdown: kramdown

# URL of the Site
url: 
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: devCiTi.
# Description of the Site
description: hundreds of articles for the tech enthusiast!!
# URL of Image of the Site
site-image: /WhatATheme/assets/images/dave.jpg
# Keywords of the Site
site-keywords: Software developer, technology, articles
# URL for the Image of custom Favicon
favicon-url: /assets/images/dave.jpg

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: devmuangi@gmail.com
facebook_username: /
codepen_username: devMuangi
instagram_username: devmuangi
linkedin_username: devmuangi
github_username:  devmuangi
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: devmuangi

# Name of the Author
author-name: devmuangi
# URL for the Image of the Author
author-image:  https://avatars3.githubusercontent.com/u/55136496?s=460&u=20d26b00fde078e5a357b05e08bc699dd6b26b32&v=4
# 60 Words About the Author
author-about: Hi. My name is Dave ,Software developer and founder of devCiTi.I publish articles every week to help all tech enthusiasts out there get up to speed with the latest trends and news.I'am currently working as a freelance developer.My go to tech stack is the MERN stack,but I can always switch according to the needs of my client.I love a challenge.Feel free to reach out to me.


# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/devmuangi

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
